### ISSUE TITLE
Redesign: Implement Word Switching for 'make/be' your MVP

### ISSUE THREAD

**Issue by ghost** [dwyl/dwyl-site#308]
https://github.com/dwyl/dwyl-site/issues/255#issuecomment-310121714
Code example: https://jsbin.com/dadinagojo/1/edit?output
Technical docs: https://www.w3schools.com/cssref/pr_background-attachment.asp

**Comment by ZooeyMiller** [comment]
How are we going to make this work in terms of accessibility? If the make/be are background properties they'll be invisible to a screen reader (as far as I know), and if the text is actual text rather than an image we won't be able to give it alt text (so a screen reader will see it as "We can your MVP".

I'm sure there's a way around it, but I just want to make sure it's something we're thinking about for this `enhancement`.

**Comment by Jbarget** [comment]
@ZooeyMiller you can hide from screen readers using [`aria-hidden=true`](
https://stackoverflow.com/questions/672156/is-there-a-way-to-write-content-that-screen-readers-will-ignore) and create a utility class called `.sr-only` that will read out what you need

```css
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  clip-path: inset(50%);
  border: 0;
}
```
